### ISSUE TITLE
Initial devcontainer setup

### ISSUE THREAD

**Issue by thekaveman** [compilerla/pems#3]
Follow outline in https://github.com/compilerla/template-devcontainer

- [ ] Based on Python 3.12
- [ ] non-root user
- [ ] `pre-commit` configuration, base on https://github.com/compilerla/template-devcontainer/blob/main/.pre-commit-config.yaml
- [ ] `.vscode/settings.json` with basics for formatting, etc. base on https://github.com/compilerla/template-devcontainer/blob/main/.vscode/settings.json

## Post-merge steps

- [ ] Activate the `pre-commit` CI bot for this repo
- [ ] Make the associated check a required check in the protection rules

**Comment by thekaveman** [comment]
@lalver1 I'll work on the post-merge steps now.

**Comment by thekaveman** [comment]
> Make the associated check a required check in the protection rules

The pre-commit CI bot is configured, but we need to trigger the check with a PR before we can do this.

**Comment by lalver1** [comment]
Thanks @thekaveman, I have a PR for issue #7  ready to go, should I create it to trigger the check?

**Comment by thekaveman** [comment]
@lalver1 thanks, I was able to see it after opening #23
