### ISSUE TITLE
Write getting started guide for local dev setup

### ISSUE THREAD

**Issue by thekaveman** [compilerla/pems#42]
- [x] prerequisites: Docker, Compose, VS Code, VS Code Dev Containers extension
- [x] cloning the repo
- [x] environment file
- [x] rebuild and reopen
- [x] ports tab

**Comment by Brijeshthummar02** [comment]
@thekaveman it should be in .md format? also show me file location where should i place it.

**Comment by thekaveman** [comment]
Hi @Brijeshthummar02, I really appreciate the offer of support. We're just getting this project started and have a full sprint with folks dedicated, so we're not looking for any external contributions at this time. Thank you anyway!
